#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Check if the script is called with the correct number of parameters
if [ "$#" -ne 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking for scp(Secure copy protocol)
SSH_OPTIONS="-o StrictHostKeyChecking=no"

# Use scp to transfer the file to the user's home dir on the server
scp "$SSH_OPTIONS" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

#Check the exit status of scp
if [ $? -eq 0 ]; then
   echo "File transfer successful."
else
   echo "File transfer failed."
fi

