#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to:
# Install nginx on your web-01, Nginx should be listening on port 80

#Install Nginx
apt-get update -y
apt-get install nginx -y

#Start Nginx
service nginx start

#Create a simples HTML file
echo "Hello World!" > /var/www/html/index.html

#Verify that Nginx is listening on port 80
netstat -tuln | grep ':80'

exit 0