#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine:
# The redirection must be a “301 Moved Permanently”

# Ensure root privileges
if [ "$(id -u)" -ne 0 ]; then
   echo "This script must be run with superuser privileges"
   exit 1
fi

# Define the redirection configuration
REDIRECTION_CONFIG="location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Add te redirection configuration to Nginx's default site configuration
echo "$REDIRECTION_CONFIG" | tee /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
service nginx reload

echo "Redirection configured successfully."