#!/usr/bin/env bash
# Check if nginx is installed
if ! command -v nginx &> /dev/null
then
    echo "Nginx is not installed. Please run the 1-install_nginx_web_server script first."
    exit 1
fi

# Create a configuration file for the redirection
echo "location /redirect_me {" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null
echo "    return 301 Moved Permanently" | sudo tee -a /etc/nginx/sites-available/redirect_me > /dev/null
echo "}" | sudo tee -a /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Reload Nginx configuration
sudo kill -s HUP $(pgrep -f "nginx: master process")

# Output success message
echo "Nginx configured to perform a 301 redirect from /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4."
