#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

#Ensure root privileges
if [ "$(id -u)" -ne 0 ]; then
   echo "This script must be run with superuser privileges."
   exit 1
fi

# Define the custome 404 page configuration
NOT_FOUND_CONFIG="error_page 404 /custom_404.html;
location = /custom_404.html {
	 root /var/www/html;
	 internal;
	 return 404 'Ceci n\'est pas une page';
}"

# Add the custom 404 page configuration to Nginx's default site configuration
echo "$NOT_FOUND_CONFIG" | tee /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
service nginx reload

echo "Custom 404 page configured successfully."