#!/usr/bin/env bash

# Check if nginx is installed
if ! command -v nginx &> /dev/null
then
    echo "Nginx is not installed. Please run the 1-install_nginx_web_server script first."
    exit 1
fi

# Create a configuration file for the custom 404 page
echo "error_page 404 /custom_404.html;" | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null
echo "location = /custom_404.html {" | sudo tee -a /etc/nginx/sites-available/custom_404 > /dev/null
echo "    internal;" | sudo tee -a /etc/nginx/sites-available/custom_404 > /dev/null
echo "    return 200 'Ceci n\\'est pas une page\n';" | sudo tee -a /etc/nginx/sites-available/custom_404 > /dev/null
echo "}" | sudo tee -a /etc/nginx/sites-available/custom_404 > /dev/null

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Reload Nginx configuration
sudo kill -s HUP $(pgrep -f "nginx: master process")

# Output success message
echo "Nginx configured to have a custom 404 page with the string 'Ceci n'est pas une page.'"
