#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
	balance roundrobin
	server web1 100.25.22.74 check
	server web2 107.23.109.220 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start