#!/usr/bin/env bash
# Configure ssh client so that you can
# connect to a server without typing a password
Host *
     SendEnv LANG LC_*
     HashKnownHosts yes
     GSSAPIAuthentication yes
     GSSAPIDelegateCredentials no
     IdentifyFile ~/.ssh/school
     PasswordAuthentication no